# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\"1\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x19\n\x0bTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x08TaskList\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task\"\x07\n\x05\x45mpty2\xc0\x01\n\x0bTaskService\x12\"\n\nCreateTask\x12\x05.Task\x1a\r.TaskResponse\x12\x1e\n\x07GetTask\x12\x0c.TaskRequest\x1a\x05.Task\x12\"\n\nUpdateTask\x12\x05.Task\x1a\r.TaskResponse\x12)\n\nDeleteTask\x12\x0c.TaskRequest\x1a\r.TaskResponse\x12\x1e\n\tListTasks\x12\x06.Empty\x1a\t.TaskListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=15
  _globals['_TASK']._serialized_end=64
  _globals['_TASKREQUEST']._serialized_start=66
  _globals['_TASKREQUEST']._serialized_end=91
  _globals['_TASKRESPONSE']._serialized_start=93
  _globals['_TASKRESPONSE']._serialized_end=124
  _globals['_TASKLIST']._serialized_start=126
  _globals['_TASKLIST']._serialized_end=158
  _globals['_EMPTY']._serialized_start=160
  _globals['_EMPTY']._serialized_end=167
  _globals['_TASKSERVICE']._serialized_start=170
  _globals['_TASKSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
